### ISSUE TITLE
Test scripts are not called in starbucks_drinks_test.py

### ISSUE THREAD

**Issue by usmanwardag** [usmanwardag/csc510_hw#4]
Currently, the file `starbucks_drinks_test.py`  does not actually test anything because the class `TestDrinks` is not being instantiated. There should be 2 changes to run these tests.

1. Add a constructor method in the class that calls all test methods.
2. Instantiate the class by creating an object of it at the end of the file.

@sbosenc @Urvashi74

**Comment by sbosenc** [comment]
Making changes
